version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      retries: 3

  createbucket:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 minioadmin minioadmin &&
        mc mb local/lakehouse-data || true
      "

  hive-metastore:
    image: apache/hive:standalone-metastore-4.1.0
    container_name: hive-metastore
    environment:
      - SERVICE_NAME=metastore
    ports:
      - "9083:9083"
    command: ["hive", "metastore"]
    volumes:
      - ./config/hive/hive-site.xml:/opt/hive/conf/hive-site.xml

  spark:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    volumes:
      - ./data:/data
    depends_on:
      - minio
      - hive-metastore

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./config/trino/catalog:/etc/trino/catalog
    depends_on:
      - hive-metastore
      - minio

volumes:
  minio_data:
